#page title
page_title                                : HR Life Counter                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                           # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://github.com/JFtechOfficial         # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/icon_android.png                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : HR Life Counter                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A companion app for the physical card game

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : JF tech                              
your_link                                 : https://github.com/JFtechOfficial                   
your_city                                 : Rome                                
email_address                             : jftech@outlook.it
facebook_username                         : JF tech                                          
instagram_username                        : jftechofficial
twitter_username                          : JFtechOfficial
github_username                           : JFtechOfficial
youtube_username                          : JF tech



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : One or more devices
    description                           : Start a simple game using a single device at the center of the table, or host a game and have every other player join with their device.
    fontawesome_icon_name                 : mobile
    
  - title                                 : Designed for Hero Realms
    description                           : Support for different game modes, characters, bosses and ancestries allows automatic calculation of starting health. (multidevice-only)
    fontawesome_icon_name                 : magic

  - title                                 : Randomizers!
    description                           : Spice up your games with per-player random assingments of characters, ancestries, team, role. First player badge is also assigned. (multidevice-only)
    fontawesome_icon_name                 : sync

  - title                                 : Keep track of life totals
    description                           : Life total of each player at a glace. When using multiple devices you can access the life total calculator and the additional combat/healing/gold pool counters.
    fontawesome_icon_name                 : plus

  - title                                 : Keep track of campaign progress
    description                           : Save the progress your hero has made to easly continue your campaign next time. (multidevice-only)
    fontawesome_icon_name                 : list
  
  - title                                 : Keep track of your collection
    description                           : See all the regular and promo sets that have been published, check the ones you own.
    fontawesome_icon_name                 : info-circle

  - title                                 : Get stats about your games
    description                           : Improve your plays by looking at your statistics from past games. 
    fontawesome_icon_name                 : chart-line

  - title                                 : Access rulebooks
    description                           : Pick a game set and browse the official rulebook. You can even search for specific words.
    fontawesome_icon_name                 : book
    
  - title                                 : Use it everywhere for free
    description                           : You don't need a data plan to host or join a multidevice game since they are hosted locally.
    fontawesome_icon_name                 : peace

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#ee4444"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ee4444"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
